name: Cobra Customs LAX
favicon: null
layout_spectrum: 0.565812254557386
typography_spectrum: 0.23374
title: Custom Lacrosse Stringing for Northwest Montana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cfbbbd'
    - '#111516'
    - '#6b7b54'
    - '#ff7980'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.34745088848285377
  rhythmicContrast: 0.4154415905941278
purpose: []
